/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CoffeShop;

/**
 *
 * @author James
 */
//import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.LayoutStyle;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

public class Dashboard extends javax.swing.JFrame {

    private ProductMethods productMethods;
    private UserAuthenticate loggedInUser; // Store the use

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();

        setTitle("Dashboard");

        // Load the icon for the dashboard window
        ImageIcon icon = IconLoader.getIcon();
        Image img = icon.getImage();
        setIconImage(img);

        setIconImage(img);
        productMethods = new ProductMethods();
        GridLayoutDisplay();

        searchText.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                handleSearch();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                handleSearch();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                handleSearch();
            }
        });

        searchText.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    // Trigger the login action when Enter is pressed
                    btnSearchActionPerformed(null);
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        employeeRoleTxt = new javax.swing.JLabel();
        UserImageIcon = new javax.swing.JLabel();
        employeNamerTxt = new javax.swing.JLabel();
        navbarLeft = new javax.swing.JPanel();
        btnOption = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        itemDetails = new javax.swing.JPanel();
        centerPanel = new javax.swing.JPanel();
        searchBar = new javax.swing.JPanel();
        searchText = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        coffeeGrid = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        teaGrid = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        snackGrid = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        productTable = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        totalLabel = new javax.swing.JLabel();
        amountLabel = new javax.swing.JLabel();
        changeLabel = new javax.swing.JLabel();
        totalFld = new javax.swing.JTextField();
        amountFld = new javax.swing.JTextField();
        changeFld = new javax.swing.JTextField();
        btnPay = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnReceipt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        header.setBackground(new java.awt.Color(81, 56, 33));

        employeeRoleTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        employeeRoleTxt.setForeground(new java.awt.Color(255, 255, 255));
        employeeRoleTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeeRoleTxt.setText("Role");

        UserImageIcon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        UserImageIcon.setForeground(new java.awt.Color(255, 255, 255));
        UserImageIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserImageIcon.setText("User");

        employeNamerTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        employeNamerTxt.setForeground(new java.awt.Color(255, 255, 255));
        employeNamerTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeNamerTxt.setText("Employee Name");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(872, Short.MAX_VALUE)
                .addComponent(employeeRoleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(employeNamerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UserImageIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeRoleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeNamerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UserImageIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        navbarLeft.setBackground(new java.awt.Color(255, 192, 135));

        btnOption.setBackground(new java.awt.Color(255, 192, 135));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/report.png"))); // NOI18N
        jButton2.setText("Reports");
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setHideActionText(true);
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.setPreferredSize(new java.awt.Dimension(80, 35));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu.png"))); // NOI18N
        jButton1.setText("Menu");
        jButton1.setToolTipText("");
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.setPreferredSize(new java.awt.Dimension(80, 35));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/product.png"))); // NOI18N
        jButton3.setText("Products");
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.setPreferredSize(new java.awt.Dimension(80, 35));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/employee.png"))); // NOI18N
        jButton4.setText("Employees");
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton4.setPreferredSize(new java.awt.Dimension(80, 35));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnOptionLayout = new javax.swing.GroupLayout(btnOption);
        btnOption.setLayout(btnOptionLayout);
        btnOptionLayout.setHorizontalGroup(
            btnOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnOptionLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(btnOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        btnOptionLayout.setVerticalGroup(
            btnOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnOptionLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout navbarLeftLayout = new javax.swing.GroupLayout(navbarLeft);
        navbarLeft.setLayout(navbarLeftLayout);
        navbarLeftLayout.setHorizontalGroup(
            navbarLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navbarLeftLayout.createSequentialGroup()
                .addComponent(btnOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        navbarLeftLayout.setVerticalGroup(
            navbarLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLeftLayout.createSequentialGroup()
                .addComponent(btnOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 566, Short.MAX_VALUE))
        );

        getContentPane().add(navbarLeft, java.awt.BorderLayout.LINE_START);

        itemDetails.setBackground(new java.awt.Color(255, 192, 135));

        centerPanel.setBackground(new java.awt.Color(142, 104, 69));

        searchBar.setBackground(new java.awt.Color(255, 245, 238));
        searchBar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        searchText.setBackground(new java.awt.Color(255, 245, 238));
        searchText.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        searchText.setForeground(new java.awt.Color(142, 104, 69));
        searchText.setText("Search");
        searchText.setToolTipText("");
        searchText.setBorder(null);
        searchText.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        searchText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchTextFocusLost(evt);
            }
        });
        searchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextActionPerformed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(142, 104, 69));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(142, 104, 69));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        btnSearch.setBorder(null);
        btnSearch.setBorderPainted(false);
        btnSearch.setContentAreaFilled(false);
        btnSearch.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSearch.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnSearch.setIconTextGap(20);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchBarLayout = new javax.swing.GroupLayout(searchBar);
        searchBar.setLayout(searchBarLayout);
        searchBarLayout.setHorizontalGroup(
            searchBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchBarLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(searchText, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch)
                .addContainerGap())
        );
        searchBarLayout.setVerticalGroup(
            searchBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(searchBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(searchBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(searchText))
                .addGap(27, 27, 27))
        );

        jTabbedPane2.setBackground(new java.awt.Color(142, 104, 69));
        jTabbedPane2.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane2.setToolTipText("");
        jTabbedPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTabbedPane2.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jTabbedPane2.setOpaque(true);

        coffeeGrid.setBackground(new java.awt.Color(255, 245, 238));
        coffeeGrid.setLayout(new java.awt.GridLayout(0, 3));
        jScrollPane1.setViewportView(coffeeGrid);

        jTabbedPane2.addTab("Coffee", jScrollPane1);

        teaGrid.setLayout(new java.awt.GridLayout(0, 3));
        jScrollPane2.setViewportView(teaGrid);

        jTabbedPane2.addTab("Tea", jScrollPane2);

        snackGrid.setLayout(new java.awt.GridLayout(0, 3));
        jScrollPane3.setViewportView(snackGrid);

        jTabbedPane2.addTab("Snacks", jScrollPane3);

        javax.swing.GroupLayout centerPanelLayout = new javax.swing.GroupLayout(centerPanel);
        centerPanel.setLayout(centerPanelLayout);
        centerPanelLayout.setHorizontalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTabbedPane2)
                    .addComponent(searchBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        centerPanelLayout.setVerticalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 192, 135));

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Price", "Quantity", "Total Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orderTable.getTableHeader().setReorderingAllowed(false);
        productTable.setViewportView(orderTable);
        if (orderTable.getColumnModel().getColumnCount() > 0) {
            orderTable.getColumnModel().getColumn(0).setResizable(false);
            orderTable.getColumnModel().getColumn(1).setResizable(false);
            orderTable.getColumnModel().getColumn(2).setResizable(false);
            orderTable.getColumnModel().getColumn(3).setResizable(false);
        }

        totalLabel.setText("Total:");

        amountLabel.setText("Amount:");

        changeLabel.setText("Change:");

        totalFld.setEditable(false);
        totalFld.setText("0");

        amountFld.setText("0");
        amountFld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                amountFldKeyReleased(evt);
            }
        });

        changeFld.setEditable(false);
        changeFld.setText("0");

        btnPay.setText("Pay");
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnReceipt.setText("Receipt");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalLabel)
                                    .addComponent(amountLabel)
                                    .addComponent(changeLabel))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(changeFld, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                    .addComponent(amountFld)
                                    .addComponent(totalFld))
                                .addGap(38, 38, 38))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(btnPay)
                                .addGap(52, 52, 52)
                                .addComponent(btnRemove))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(btnReceipt)))
                        .addGap(126, 126, 126))
                    .addComponent(productTable, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(productTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalLabel))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(amountLabel)
                    .addComponent(amountFld, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(changeLabel)
                    .addComponent(changeFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPay)
                    .addComponent(btnRemove))
                .addGap(26, 26, 26)
                .addComponent(btnReceipt)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout itemDetailsLayout = new javax.swing.GroupLayout(itemDetails);
        itemDetails.setLayout(itemDetailsLayout);
        itemDetailsLayout.setHorizontalGroup(
            itemDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemDetailsLayout.createSequentialGroup()
                .addComponent(centerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        itemDetailsLayout.setVerticalGroup(
            itemDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(centerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(itemDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(226, Short.MAX_VALUE))
        );

        getContentPane().add(itemDetails, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1335, 1009));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Dashboard callDashboard = new Dashboard();
        callDashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String searchTerm = searchText.getText().trim(); // Get the search term from the text field
        searchMenu(searchTerm);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void searchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextActionPerformed

    }//GEN-LAST:event_searchTextActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Products callProducts = new Products();
        callProducts.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Employees callEmployees = new Employees();
        callEmployees.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Reports callReports = new Reports();
        callReports.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        GridLayoutDisplay();

        // Set user details if available
        if (loggedInUser != null) {
            setUserDetails(loggedInUser);
        } else {
            System.out.println("User details not set yet.");
        }

    }//GEN-LAST:event_formWindowOpened

    private void searchTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTextFocusGained
        if (searchText.getText().equals("Search")) {
            searchText.setText("");
            searchText.setForeground(Color.BLACK); // Optional: Change text color to black
        }
    }//GEN-LAST:event_searchTextFocusGained

    private void searchTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTextFocusLost
        if (searchText.getText().isEmpty()) {
            searchText.setText("Search");
            searchText.setForeground(Color.GRAY); // Change text color to gray
        }
    }//GEN-LAST:event_searchTextFocusLost

    private void amountFldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountFldKeyReleased
        // TODO add your handling code here:
        // Get the amount entered in the amountFld
        String amountText = amountFld.getText();

        // Try to parse the amount to a double
        try {
            double amount = Double.parseDouble(amountText);

            // Calculate the total price using your updated method
            double totalPrice = calculateTotalPrice(); // This now returns the total price

            // Calculate the change amount
            double change = amount - totalPrice;

            // Display the change in changeFld
            changeFld.setText(String.format("%.2f", change)); // Format the change to 2 decimal places

        } catch (NumberFormatException e) {
            // Handle the case where the input is not a valid double
            changeFld.setText("0.00"); // Reset changeFld if input is invalid
        }
    }//GEN-LAST:event_amountFldKeyReleased

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        DefaultTableModel model = (DefaultTableModel) orderTable.getModel();

        // Clear all rows from the table
        model.setRowCount(0);

        
        // Reset the fields after successful sale
            amountFld.setText("0"); // Reset amount field
            changeFld.setText("0"); // Reset change field
            totalFld.setText("0"); // Reset total field (if you have a totalFld)
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        // Check if there are any items in the order table
        DefaultTableModel model = (DefaultTableModel) orderTable.getModel();
        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No items in the order to proceed with the payment.", "Warning", JOptionPane.WARNING_MESSAGE);
            return; // Exit if the order table is empty
        }

        // Retrieve amount and change from the input fields
        double amount = 0.0;
        double amountChange = 0.0;

        try {
            // Get amount from the amountFld JTextField
            amount = Double.parseDouble(amountFld.getText());
            // Get change from the changeFld JTextField
            amountChange = Double.parseDouble(changeFld.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid amount or change value.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Exit if the values are invalid
        }

        // Check for validation conditions
        if (amount <= 0) {
            JOptionPane.showMessageDialog(this, "The amount must be greater than zero.", "Warning", JOptionPane.WARNING_MESSAGE);
            return; // Exit if the amount is zero or less
        }

        if (amountChange < 0) {
            JOptionPane.showMessageDialog(this, "Change cannot be negative.", "Warning", JOptionPane.WARNING_MESSAGE);
            return; // Exit if the change is negative
        }

        // Show confirmation dialog
        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to proceed with this sale?",
                "Confirm Sale",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        // If the user confirmed the sale
        if (confirm == JOptionPane.YES_OPTION) {
            // Call the method to add the sale
            addSales(); // This calls your addSales method to process the transaction

            // Reset the fields after successful sale
            amountFld.setText("0"); // Reset amount field
            changeFld.setText("0"); // Reset change field
            totalFld.setText("0"); // Reset total field (if you have a totalFld)

            // Notify user of success
            JOptionPane.showMessageDialog(this, "Sale added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

            // Optionally clear the order table after sale
            model.setRowCount(0); // Clear order table
        } else {
            // User cancelled the transaction
            JOptionPane.showMessageDialog(this, "Transaction cancelled.", "Cancelled", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnPayActionPerformed

    private void handleSearch() {
        String searchTerm = searchText.getText().trim();  // Get the search term

        if (searchTerm.isEmpty()) {
            // If the search term is empty, reset to display the full menu
            GridLayoutDisplay();
        } else {
            // Perform the search and update the grids
            searchMenu(searchTerm);
        }
    }

    private void searchMenu(String searchTerm) {
        if (searchTerm.isEmpty()) {
            GridLayoutDisplay(); // This will reset and display the full menu
            return;
        }
        // Clear the existing product displays
        coffeeGrid.removeAll();
        teaGrid.removeAll();
        snackGrid.removeAll();

        // Fetch products based on search term (not dynamically)
        List<Product> products = productMethods.searchMenuMethod(searchTerm);

        // Iterate over the products list and create UI components for each product
        for (Product product : products) {
            JPanel productPanel = createProductPanel(product);
            // Add the product panel to the corresponding grid based on the category
            switch (product.getProductCategory()) {
                case "Coffee":
                    coffeeGrid.add(productPanel);
                    break;
                case "Tea":
                    teaGrid.add(productPanel);
                    break;
                case "Snacks":
                    snackGrid.add(productPanel);
                    break;
                default:
                    break;
            }
        }

        // Refresh each grid panel
        coffeeGrid.revalidate();
        coffeeGrid.repaint();
        teaGrid.revalidate();
        teaGrid.repaint();
        snackGrid.revalidate();
        snackGrid.repaint();
    }

    private void GridLayoutDisplay() {
        // Clear existing components in each grid
        coffeeGrid.removeAll();
        teaGrid.removeAll();
        snackGrid.removeAll();

        List<Product> products = productMethods.productMethod(); // Fetch products from the database

        // Iterate over the products list and create UI components for each product
        for (Product product : products) {
            JPanel productPanel = createProductPanel(product);
            // Add the product panel to the corresponding grid based on the category
            switch (product.getProductCategory()) {
                case "Coffee":
                    coffeeGrid.add(productPanel);
                    break;
                case "Tea":
                    teaGrid.add(productPanel);
                    break;
                case "Snacks":
                    snackGrid.add(productPanel);
                    break;
                default:
                    break;
            }
        }

        // Refresh each grid panel
        coffeeGrid.revalidate();
        coffeeGrid.repaint();
        teaGrid.revalidate();
        teaGrid.repaint();
        snackGrid.revalidate();
        snackGrid.repaint();
    }

    private ImageIcon resizeImage(String imagePath, int width, int height) {
        // Load the image
        ImageIcon originalIcon = new ImageIcon(imagePath);
        Image originalImage = originalIcon.getImage();

        // Resize the image
        Image resizedImage = originalImage.getScaledInstance(width, height, Image.SCALE_SMOOTH);

        // Return the resized ImageIcon
        return new ImageIcon(resizedImage);
    }

    public void setUserDetails(UserAuthenticate user) {
        this.loggedInUser = user;

        if (loggedInUser != null) {
            employeeRoleTxt.setText(loggedInUser.getRole());
            employeNamerTxt.setText(loggedInUser.getName());

            // Resize and set employee image icon
            ImageIcon userImage = resizeImage(loggedInUser.getImagePath(), 60, 60);
            UserImageIcon.setIcon(userImage);
        } else {
            System.out.println("User details not set.");
        }
    }

    // Method to set loggedInUser before the form opens
    public void setLoggedInUser(UserAuthenticate user) {
        this.loggedInUser = user;
    }

    private JPanel createProductPanel(Product product) {
        JPanel productPanel = new JPanel();
        Color customColor = new Color(230, 155, 87);
        productPanel.setBorder(BorderFactory.createLineBorder(customColor, 1));
        productPanel.setBackground(new Color(255, 245, 238));

        // Set up image label
        JLabel imageLabel = new JLabel();
        ImageIcon productImage = new ImageIcon(product.getProductImagePath());
        Image scaledImage = resizeImage(productImage, 100, 200);
        imageLabel.setIcon(new ImageIcon(scaledImage));
        imageLabel.setHorizontalAlignment(JLabel.CENTER);

        // Set up name and price labels
        JLabel nameLabel = new JLabel(product.getProductName());
        JLabel priceLabel = new JLabel("₱" + String.format("%.2f", product.getProductPrice()));

        Font justFont = new Font("Segoe UI", Font.BOLD, 14);
        Font boldFont = new Font("Arial", Font.PLAIN, 14);
        nameLabel.setFont(boldFont);
        priceLabel.setFont(justFont);

        // Set up quantity spinner
        JSpinner quantitySpinner = new JSpinner(new SpinnerNumberModel(1, 1, 100, 1));

        // Set up add button
        JButton addButton = new JButton("Add");
        addButton.setBackground(new Color(255, 167, 87));
        addButton.setForeground(new Color(81, 56, 33));
        addButton.setBorderPainted(false);
        addButton.setFocusPainted(false);
        addButton.setContentAreaFilled(true);
        Font boldAdd = addButton.getFont().deriveFont(Font.BOLD);
        addButton.setFont(boldAdd);

        // Add action listener to the Add button
        addButton.addActionListener(e -> {
            String productName = product.getProductName();
            double productPrice = product.getProductPrice();
            int quantity = (int) quantitySpinner.getValue();

            // Add the product to the order table
            addToOrderTable(productName, quantity, productPrice);

            // Reset the spinner value back to 1
            quantitySpinner.setValue(1);
        });

        // Set up layout for the product panel
        GroupLayout productPanelLayout = new GroupLayout(productPanel);
        productPanel.setLayout(productPanelLayout);

        productPanelLayout.setHorizontalGroup(
                productPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(productPanelLayout.createParallelGroup(GroupLayout.Alignment.CENTER)
                                .addComponent(imageLabel, GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(nameLabel, GroupLayout.Alignment.CENTER)
                                .addGroup(productPanelLayout.createSequentialGroup()
                                        .addComponent(priceLabel, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(quantitySpinner, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(addButton, GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap()
        );

        productPanelLayout.setVerticalGroup(
                productPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGap(15)
                        .addComponent(nameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(imageLabel, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(productPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(priceLabel)
                                .addComponent(quantitySpinner)
                                .addComponent(addButton))
                        .addGap(15)
                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        productPanel.revalidate();
        productPanel.repaint();
        return productPanel;
    }

    private Image resizeImage(ImageIcon originalImage, int targetWidth, int targetHeight) {
        // Get the original dimensions
        int originalWidth = originalImage.getIconWidth();
        int originalHeight = originalImage.getIconHeight();

        // Maintain aspect ratio
        double aspectRatio = (double) originalWidth / originalHeight;
        if (originalWidth > originalHeight) {
            targetHeight = (int) (targetWidth / aspectRatio);
        } else {
            targetWidth = (int) (targetHeight * aspectRatio);
        }

        return originalImage.getImage().getScaledInstance(targetWidth, targetHeight, Image.SCALE_SMOOTH);
    }

    private void addToOrderTable(String productName, int quantity, double price) {
        DefaultTableModel model = (DefaultTableModel) orderTable.getModel();

        // Validate inputs
        if (productName.isEmpty() || quantity <= 0 || price <= 0) {
            JOptionPane.showMessageDialog(this, "Please provide valid product details", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Calculate total price for the new quantity
        double totalPrice = quantity * price;

        // Flag to check if the product already exists
        boolean productExists = false;

        // Check if the product already exists in the table
        for (int i = 0; i < model.getRowCount(); i++) {
            String existingProductName = (String) model.getValueAt(i, 0); // Assuming product name is in column 0
            if (existingProductName.equals(productName)) {
                // Update the quantity and total price for the existing product
                int existingQuantity = (int) model.getValueAt(i, 2); // Assuming quantity is in column 2
                double existingTotalPrice = (double) model.getValueAt(i, 3); // Assuming total price is in column 3

                // Update the quantity and total price
                model.setValueAt(existingQuantity + quantity, i, 2); // Update quantity
                model.setValueAt(existingTotalPrice + totalPrice, i, 3); // Update total price

                productExists = true;
                break; // Exit the loop as we found the product
            }
        }

        // If the product doesn't exist, add a new row
        if (!productExists) {
            model.addRow(new Object[]{
                productName, // Product Name
                price, // Price
                quantity, // Quantity
                totalPrice // Total Price
            });
        }

        // Update the total price displayed in totalFld
        calculateTotalPrice();
        updateChangeAmount();
    }

    private void updateChangeAmount() {
        // Get the amount entered in the amountFld
        String amountText = amountFld.getText();

        // Try to parse the amount to a double
        try {
            double amount = Double.parseDouble(amountText);

            // Calculate the total price using your updated method
            double totalPrice = calculateTotalPrice(); // This now returns the total price

            // Calculate the change amount
            double change = amount - totalPrice;

            // Display the change in changeFld
            changeFld.setText(String.format("%.2f", change)); // Format the change to 2 decimal places

        } catch (NumberFormatException e) {
            // Handle the case where the input is not a valid double
            changeFld.setText("0.00"); // Reset changeFld if input is invalid
        }
    }

    private double calculateTotalPrice() {
        DefaultTableModel model = (DefaultTableModel) orderTable.getModel();
        double totalPriceSum = 0;

        // Loop through all rows and sum the total price column (assumed to be at index 3)
        for (int i = 0; i < model.getRowCount(); i++) {
            // Assuming the total price is stored as a double in column 3
            Object totalPriceObject = model.getValueAt(i, 3);
            double rowTotalPrice = 0;

            // Check the type of total price and cast accordingly
            if (totalPriceObject instanceof Double) {
                rowTotalPrice = (Double) totalPriceObject;
            } else if (totalPriceObject instanceof Integer) {
                rowTotalPrice = (Integer) totalPriceObject; // Cast as Integer
            }

            totalPriceSum += rowTotalPrice;
        }

        // Display the total sum in the JTextField totalFld
        totalFld.setText(String.format("%.2f", totalPriceSum)); // Format to 2 decimal places

        // Return the calculated total price
        return totalPriceSum;
    }

    private void addSales() {
        // Check if there are any items in the order table
        DefaultTableModel model = (DefaultTableModel) orderTable.getModel();
        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No items in the order to add a sale.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Retrieve employee ID correctly
        int employeeId = 0;
        try {
            // Assuming getId() method returns the employee ID as a string
            employeeId = Integer.parseInt(loggedInUser.getId());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid employee ID.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Exit if the ID is invalid
        }

        String employeeName = loggedInUser.getName();
        double subtotal = 0.0;
        double vat = 0.0; // You can define how VAT is calculated
        double total = 0.0;

        List<SaleItem> saleItems = new ArrayList<>();

        // Loop through the order table to collect sale items and calculate totals
        for (int i = 0; i < model.getRowCount(); i++) {
            String productName = (String) model.getValueAt(i, 0);
            double price = (Double) model.getValueAt(i, 1);
            int quantity = (Integer) model.getValueAt(i, 2);
            double itemTotalPrice = (Double) model.getValueAt(i, 3);

            subtotal += itemTotalPrice; // Update subtotal
            total += itemTotalPrice; // Update total

            // Create SaleItem and add to the list
            int productId = getProductIdByName(productName); // Get the product ID
            if (productId <= 0) {
                JOptionPane.showMessageDialog(this, "Product not found: " + productName, "Error", JOptionPane.ERROR_MESSAGE);
                return; // Exit if the product ID is invalid
            }
            saleItems.add(new SaleItem(productId, quantity, price));
        }

        // Calculate VAT (example: 12% of subtotal)
        vat = subtotal * 0.12; // Adjust VAT calculation as needed
        total = subtotal + vat;

        // Get amount and change from fields
        double amount = 0.0;
        double amountChange = 0.0;

        try {
            amount = Double.parseDouble(amountFld.getText()); // Get amount from amountFld
            amountChange = Double.parseDouble(changeFld.getText()); // Get change from changeFld
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid amount or change value.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Exit if the values are invalid
        }

        // Create an instance of SalesManagementMethod to add the sale
        SalesManagementMethod salesManager = new SalesManagementMethod();
        salesManager.addSale(employeeId, employeeName, subtotal, vat, total, amount, amountChange, saleItems);

        // Notify user of success
        JOptionPane.showMessageDialog(this, "Sale added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

        // Optionally clear the order table after sale
        model.setRowCount(0); // Clear order table
    }

    private int getProductIdByName(String productName) {
        int productId = 0; // Placeholder for product ID
        String query = "SELECT product_id FROM tbl_products WHERE product_name = ?"; // Updated SQL query

        sqlConnector callConnector = new sqlConnector();

        try (Connection conn = callConnector.createConnection(); PreparedStatement stmt = conn.prepareStatement(query)) {
            stmt.setString(1, productName);
            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
                productId = rs.getInt("product_id"); // Use the correct column name
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

        return productId; // Return the found product ID
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UserImageIcon;
    private javax.swing.JTextField amountFld;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JPanel btnOption;
    private javax.swing.JButton btnPay;
    private javax.swing.JButton btnReceipt;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSearch;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JTextField changeFld;
    private javax.swing.JLabel changeLabel;
    private javax.swing.JPanel coffeeGrid;
    private javax.swing.JLabel employeNamerTxt;
    private javax.swing.JLabel employeeRoleTxt;
    private javax.swing.JPanel header;
    private javax.swing.JPanel itemDetails;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPanel navbarLeft;
    private javax.swing.JTable orderTable;
    private javax.swing.JScrollPane productTable;
    private javax.swing.JPanel searchBar;
    private javax.swing.JTextField searchText;
    private javax.swing.JPanel snackGrid;
    private javax.swing.JPanel teaGrid;
    private javax.swing.JTextField totalFld;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
