/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CoffeShop;

import java.awt.Image;
import java.math.BigDecimal;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jenal
 */
public class Reports extends javax.swing.JFrame {

    private UserAuthenticate authenticatedUser; // Instance variable
    private ReportMethods reportMethods; // Instance of ReportMethods

    /**
     * Creates new form Reports
     */
    public Reports() {

        initComponents();

        setTitle("Reports");

        ImageIcon icon = IconLoader.getIcon();
        Image img = icon.getImage();

        setIconImage(img);
        refreshReport();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        employeeRoleTxt = new javax.swing.JLabel();
        UserImageIcon = new javax.swing.JLabel();
        employeNamerTxt = new javax.swing.JLabel();
        logutIcon = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        navbarLeft = new javax.swing.JPanel();
        btnOption = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        itemDetails = new javax.swing.JPanel();
        centerPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        frequencyComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        salesTxtNumber = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        bestSellerComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        bestSellerQuatityTxt3 = new javax.swing.JLabel();
        bestSellerQuatityTxt4 = new javax.swing.JLabel();
        bestSellerQuatityTxt = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        coffeeBeSLQuatityText = new javax.swing.JLabel();
        teaBeSLQuatityText = new javax.swing.JLabel();
        snacksBeSLQuatityText = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        coffeeBeSLProductNameText = new javax.swing.JLabel();
        teaBeSLProductNameText = new javax.swing.JLabel();
        snacksBeSLProductNameText = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        salesTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemSalesTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        header.setBackground(new java.awt.Color(81, 56, 33));

        employeeRoleTxt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        employeeRoleTxt.setForeground(new java.awt.Color(255, 255, 255));
        employeeRoleTxt.setText("User");
        employeeRoleTxt.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        UserImageIcon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        UserImageIcon.setForeground(new java.awt.Color(255, 255, 255));
        UserImageIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        employeNamerTxt.setForeground(new java.awt.Color(255, 255, 255));
        employeNamerTxt.setText("Employee Name");
        employeNamerTxt.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        logutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        logutIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logutIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logutIconMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 245, 238));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Sales Report");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(UserImageIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(employeNamerTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(employeeRoleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 297, Short.MAX_VALUE)
                .addComponent(logutIcon)
                .addGap(30, 30, 30))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(employeeRoleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(employeNamerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addComponent(UserImageIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logutIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        navbarLeft.setBackground(new java.awt.Color(255, 192, 135));

        btnOption.setBackground(new java.awt.Color(255, 192, 135));
        btnOption.setPreferredSize(new java.awt.Dimension(167, 341));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/report.png"))); // NOI18N
        jButton2.setText("Reports");
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setHideActionText(true);
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton2.setIconTextGap(8);
        jButton2.setPreferredSize(new java.awt.Dimension(80, 35));
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu.png"))); // NOI18N
        jButton1.setText("Menu");
        jButton1.setToolTipText("");
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.setIconTextGap(8);
        jButton1.setPreferredSize(new java.awt.Dimension(80, 35));
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/product.png"))); // NOI18N
        jButton3.setText("Products");
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton3.setIconTextGap(8);
        jButton3.setPreferredSize(new java.awt.Dimension(80, 35));
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/employee.png"))); // NOI18N
        jButton4.setText("Employees");
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton4.setIconTextGap(8);
        jButton4.setPreferredSize(new java.awt.Dimension(80, 35));
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnOptionLayout = new javax.swing.GroupLayout(btnOption);
        btnOption.setLayout(btnOptionLayout);
        btnOptionLayout.setHorizontalGroup(
            btnOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnOptionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnOptionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        btnOptionLayout.setVerticalGroup(
            btnOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnOptionLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout navbarLeftLayout = new javax.swing.GroupLayout(navbarLeft);
        navbarLeft.setLayout(navbarLeftLayout);
        navbarLeftLayout.setHorizontalGroup(
            navbarLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLeftLayout.createSequentialGroup()
                .addComponent(btnOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        navbarLeftLayout.setVerticalGroup(
            navbarLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLeftLayout.createSequentialGroup()
                .addComponent(btnOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 285, Short.MAX_VALUE))
        );

        getContentPane().add(navbarLeft, java.awt.BorderLayout.LINE_START);

        itemDetails.setBackground(new java.awt.Color(255, 192, 135));
        itemDetails.setLayout(new java.awt.BorderLayout());

        centerPanel.setBackground(new java.awt.Color(142, 104, 69));
        centerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 237, 178));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.darkGray));

        jPanel4.setBackground(new java.awt.Color(255, 237, 178));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        frequencyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Daily", "Weekly", "Monthly", "Yearly" }));
        frequencyComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frequencyComboBoxActionPerformed(evt);
            }
        });
        jPanel4.add(frequencyComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 26, 127, 34));

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Period");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 26, 55, 34));

        salesTxtNumber.setBackground(new java.awt.Color(255, 221, 187));
        salesTxtNumber.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        salesTxtNumber.setForeground(new java.awt.Color(81, 56, 33));
        salesTxtNumber.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        salesTxtNumber.setText("0");
        salesTxtNumber.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        salesTxtNumber.setOpaque(true);
        jPanel4.add(salesTxtNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 78, 364, -1));

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(53, 36, 20));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sales.png"))); // NOI18N
        jLabel3.setText("Sales");
        jLabel3.setIconTextGap(5);
        jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 161, -1));

        jPanel5.setBackground(new java.awt.Color(255, 221, 187));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bestSellerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Daily", "Weekly", "Monthly", "Yearly" }));
        bestSellerComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bestSellerComboBoxActionPerformed(evt);
            }
        });
        jPanel5.add(bestSellerComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 29, 127, 34));

        jLabel4.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Period");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 33, 54, 30));

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(53, 36, 20));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bestSeller.png"))); // NOI18N
        jLabel6.setText("Item Sales");
        jLabel6.setToolTipText("");
        jLabel6.setIconTextGap(1);
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 328, 69));

        jPanel7.setBackground(new java.awt.Color(255, 221, 187));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(170, 139, 108));
        jLabel8.setText("Category");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 20));

        bestSellerQuatityTxt3.setFont(new java.awt.Font("Segoe Script", 0, 22)); // NOI18N
        bestSellerQuatityTxt3.setForeground(new java.awt.Color(81, 56, 33));
        bestSellerQuatityTxt3.setText("Cofee:");
        jPanel7.add(bestSellerQuatityTxt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 88, -1));

        bestSellerQuatityTxt4.setFont(new java.awt.Font("Segoe Script", 0, 22)); // NOI18N
        bestSellerQuatityTxt4.setForeground(new java.awt.Color(81, 56, 33));
        bestSellerQuatityTxt4.setText("Tea:");
        jPanel7.add(bestSellerQuatityTxt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 88, -1));

        bestSellerQuatityTxt.setFont(new java.awt.Font("Segoe Script", 0, 22)); // NOI18N
        bestSellerQuatityTxt.setForeground(new java.awt.Color(81, 56, 33));
        bestSellerQuatityTxt.setText("Snacks:");
        jPanel7.add(bestSellerQuatityTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(170, 139, 108));
        jLabel7.setText("Quantity");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 80, 20));

        coffeeBeSLQuatityText.setFont(new java.awt.Font("SimSun", 0, 24)); // NOI18N
        coffeeBeSLQuatityText.setForeground(new java.awt.Color(81, 56, 33));
        coffeeBeSLQuatityText.setText("0");
        jPanel7.add(coffeeBeSLQuatityText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 80, 30));

        teaBeSLQuatityText.setFont(new java.awt.Font("SimSun", 0, 24)); // NOI18N
        teaBeSLQuatityText.setForeground(new java.awt.Color(81, 56, 33));
        teaBeSLQuatityText.setText("0");
        jPanel7.add(teaBeSLQuatityText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 80, 30));

        snacksBeSLQuatityText.setFont(new java.awt.Font("SimSun", 0, 24)); // NOI18N
        snacksBeSLQuatityText.setForeground(new java.awt.Color(81, 56, 33));
        snacksBeSLQuatityText.setText("0");
        jPanel7.add(snacksBeSLQuatityText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 80, 30));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(170, 139, 108));
        jLabel9.setText("Product Name");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 150, 20));

        coffeeBeSLProductNameText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        coffeeBeSLProductNameText.setForeground(new java.awt.Color(81, 56, 33));
        coffeeBeSLProductNameText.setText("jLabel2");
        jPanel7.add(coffeeBeSLProductNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 210, 28));

        teaBeSLProductNameText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        teaBeSLProductNameText.setForeground(new java.awt.Color(81, 56, 33));
        teaBeSLProductNameText.setText("jLabel2");
        jPanel7.add(teaBeSLProductNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 210, 31));

        snacksBeSLProductNameText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        snacksBeSLProductNameText.setForeground(new java.awt.Color(81, 56, 33));
        snacksBeSLProductNameText.setText("jLabel2");
        jPanel7.add(snacksBeSLProductNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 210, 30));

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 82, -1, 170));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        centerPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 15, -1, 250));

        jPanel6.setBackground(new java.awt.Color(142, 104, 69));

        jTabbedPane1.setBackground(new java.awt.Color(255, 221, 187));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(940, 280));

        jPanel2.setBackground(new java.awt.Color(255, 241, 195));
        jPanel2.setPreferredSize(new java.awt.Dimension(940, 280));

        salesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Sale ID", "Date ", "Employee", "Amount", "Change", "Sub Total", "VAT", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(salesTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Sales", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 221, 187));
        jPanel3.setPreferredSize(new java.awt.Dimension(940, 280));

        itemSalesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ));
        jScrollPane1.setViewportView(itemSalesTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Item Sales", jPanel3);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        centerPanel.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 266, 950, 320));

        itemDetails.add(centerPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(itemDetails, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1148, 709));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private ImageIcon resizeImage(String imagePath, int width, int height) {
        // Load the image
        ImageIcon originalIcon = new ImageIcon(imagePath);
        Image originalImage = originalIcon.getImage();
        // Resize the image
        Image resizedImage = originalImage.getScaledInstance(width, height, Image.SCALE_SMOOTH);
        // Return the resized ImageIcon
        return new ImageIcon(resizedImage);
    }

    // Setter method to pass and display authenticatedUser details
    public void setAuthenticatedUser(UserAuthenticate authenticatedUser) {
        this.authenticatedUser = authenticatedUser;
        setUserDetails(authenticatedUser); // Update UI based on user details
    }

    // Method to set and display user details (name, role, and image)
    public void setUserDetails(UserAuthenticate authenticatedUser) {
        this.authenticatedUser = authenticatedUser; // Set the authenticatedUser passed

        if (authenticatedUser != null) {
            // Assuming these are your GUI builder variable names for the components
            employeeRoleTxt.setText(authenticatedUser.getRole());
            employeNamerTxt.setText(authenticatedUser.getName());

            // Resize and set employee image icon
            ImageIcon userImage = resizeImage(authenticatedUser.getImagePath(), 60, 60); // Adjust size as needed
            UserImageIcon.setIcon(userImage);
        } else {
            System.out.println("User details not set.");
        }
    }


    // Method to refresh the sales report and total sales
    private void refreshReport() {
        ReportMethods reportMethods = new ReportMethods();

        // Update the sales report table
        DefaultTableModel model = reportMethods.getSalesReportModel();
        salesTable.setModel(model); // Update the table with sales data

        // Calculate and display total sales based on the selected frequency
        calculateTotalSales();

        // Refresh the best-selling products based on the selected frequency
        refreshBestSellers(); // Add this line to also refresh best sellers
    }

    // Method to calculate total sales
    private void calculateTotalSales() {
        ReportMethods reportMethods = new ReportMethods();

        // Get the selected frequency from the ComboBox
        String selectedFrequency = (String) frequencyComboBox.getSelectedItem(); // Ensure this returns a valid value

        if (selectedFrequency != null) { // Check if a selection is made
            System.out.println("Selected Frequency: " + selectedFrequency); // Print selected frequency
            BigDecimal totalSales = reportMethods.calculateTotalSales(selectedFrequency); // Call the method

            // Update the label to display total sales
            salesTxtNumber.setText(String.format("Total Sales: ₱%.2f", totalSales));
        } else {
            salesTxtNumber.setText("Total Sales: ₱0.00"); // Handle case where no selection is made
        }
    }

    // Method to refresh the best-selling products based on the selected frequency
    // Method to refresh the best-selling products based on the selected frequency
// Method to refresh the best-selling products based on the selected frequency
    private void refreshBestSellers() {
        ReportMethods reportMethods = new ReportMethods();
        String selectedFrequency = (String) bestSellerComboBox.getSelectedItem();

        if (selectedFrequency != null) {
            System.out.println("Selected Frequency: " + selectedFrequency);

            // Call getBestSellerProduct with all required JTextField parameters
            reportMethods.getBestSellerProduct(
                    selectedFrequency,
                    coffeeBeSLProductNameText, // These are JTextField variables
                    coffeeBeSLQuatityText,
                    teaBeSLProductNameText,
                    teaBeSLQuatityText,
                    snacksBeSLProductNameText,
                    snacksBeSLQuatityText
            );

        } else {
            // Clear text fields if no selection
            coffeeBeSLProductNameText.setText("");
            coffeeBeSLQuatityText.setText("0");
            teaBeSLProductNameText.setText("");
            teaBeSLQuatityText.setText("0");
            snacksBeSLProductNameText.setText("");
            snacksBeSLQuatityText.setText("0");
        }
    }


    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        ReportMethods reportMethods = new ReportMethods();

        salesTable.setModel(reportMethods.getSalesReportModel()); // Set the model for the sales table
        itemSalesTable.setModel(reportMethods.getSalesItemsReportModel()); // Set the model for the sales items table
    }//GEN-LAST:event_formWindowActivated

    private void frequencyComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frequencyComboBoxActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        System.out.println("ComboBox selection changed to: " + frequencyComboBox.getSelectedItem());
        calculateTotalSales(); // This will invoke the method to calculate and update the total sales
    }//GEN-LAST:event_frequencyComboBoxActionPerformed

    private void bestSellerComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bestSellerComboBoxActionPerformed
        // TODO add your handling code here:
        refreshBestSellers();
    }//GEN-LAST:event_bestSellerComboBoxActionPerformed

    private void logutIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logutIconMouseClicked
        // TODO add your handling code here:
        Login callLogin = new Login();
        callLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logutIconMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Reports callReports = new Reports();
        callReports.setAuthenticatedUser(authenticatedUser); // Pass the authenticated user
        callReports.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Dashboard callDashboard = new Dashboard(); // Instantiate Dashboard
        callDashboard.setAuthenticatedUser(authenticatedUser); // Pass the authenticated user
        callDashboard.setVisible(true);
        this.dispose(); // Close the current frame
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Products callProducts = new Products();
        callProducts.setAuthenticatedUser(authenticatedUser); // Pass the authenticated user;
        callProducts.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Employees callEmployees = new Employees();
        callEmployees.setAuthenticatedUser(authenticatedUser); // Pass the authenticated user
        callEmployees.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UserImageIcon;
    private javax.swing.JComboBox<String> bestSellerComboBox;
    private javax.swing.JLabel bestSellerQuatityTxt;
    private javax.swing.JLabel bestSellerQuatityTxt3;
    private javax.swing.JLabel bestSellerQuatityTxt4;
    private javax.swing.JPanel btnOption;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JLabel coffeeBeSLProductNameText;
    private javax.swing.JLabel coffeeBeSLQuatityText;
    private javax.swing.JLabel employeNamerTxt;
    private javax.swing.JLabel employeeRoleTxt;
    private javax.swing.JComboBox<String> frequencyComboBox;
    private javax.swing.JPanel header;
    private javax.swing.JPanel itemDetails;
    private javax.swing.JTable itemSalesTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel logutIcon;
    private javax.swing.JPanel navbarLeft;
    private javax.swing.JTable salesTable;
    private javax.swing.JLabel salesTxtNumber;
    private javax.swing.JLabel snacksBeSLProductNameText;
    private javax.swing.JLabel snacksBeSLQuatityText;
    private javax.swing.JLabel teaBeSLProductNameText;
    private javax.swing.JLabel teaBeSLQuatityText;
    // End of variables declaration//GEN-END:variables
}
