INSERT INTO `tbl_products` (`product_name`, `product_category`, `product_price`, `product_ImagePath`) VALUES
('Classic Brewed Coffee', 'Coffee', 70.00, 'src\\products\\Brewed Coffee toon.jpg'),
('French Pressed Brewed Coffee', 'Coffee', 90.00, 'src\\products\\Brewed toon.jpg'),
('Caffe Latte', 'Coffee', 90.00, 'src\\products\\Caffe Latte hot.jpg'),
('Cappuccino', 'Coffee', 90.00, 'src\\products\\cappuccino hot.jpg'),
('Caffe Mocha', 'Coffee', 100.00, 'src\\products\\ coffee mocha hot.jpg'),
('Caramel Macchiato', 'Coffee', 105.00, 'src\\products\\caramel Macchiato hot.jpg'),
('Caramel Latte', 'Coffee', 105.00, 'src\\products\\caramel latte hot.jpg'),
('Almond Latte', 'Coffee', 105.00, 'src\\products\\Almond Latte Hot.jpg'),
('Vanilla Latte', 'Coffee', 105.00, 'src\\products\\Vanilla Latte Hot.jpg'),
('Praline Mocha', 'Coffee', 110.00, 'src\\products\\Praline Mocha Hot.jpg'),
('Almond Praline', 'Coffee', 110.00, 'src\\products\\Almond Praline Hot.jpg'),
('Dark Mocha', 'Coffee', 120.00, 'src\\products\\Dark Mocha Iced.jpg'),
('White Mocha', 'Coffee', 120.00, 'src\\products\\Vanilla Latte Hot.jpg'),
('Iced Caffe Latte', 'Coffee', 110.00, 'src\\products\\Caffe Latte Iced.png'),
('Coffee Jelly', 'Coffee', 130.00, 'src\\products\\Coffee Jelly iced.jpg'),
('Iced Caffe Mocha', 'Coffee', 130.00, 'src\\products\\Caffe Mocha Iced.jpg'),
('Iced Caramel', 'Coffee', 130.00, 'src\\products\\caramel Iced.jpg'),
('Iced Almond Latte', 'Coffee', 130.00, 'src\\products\\Almond Praline Iced.jpg'),
('Iced Caramel Macchiato', 'Coffee', 135.00, 'src\\products\\Caramel Macchiato Iced.jpg'),
('Iced Creamy Vanilla', 'Coffee', 140.00, 'src\\products\\Creamy Vanilla.png'),
('Iced Praline Mocha', 'Coffee', 145.00, 'src\\products\\Almond Praline Hot.jpg'),
('Iced Almond Praline', 'Coffee', 145.00, 'src\\products\\Praline Mocha Iced.jpg'),
('Iced Dark Mocha', 'Coffee', 145.00, 'src\\products\\Dark Mocha Iced.jpg'),
('Iced White Mocha', 'Coffee', 145.00, 'src\\products\\White Mocha Iced.jpg'),
('Mocha Frappe', 'Coffee', 140.00, 'src\\products\\Mocha Frappes.jpg'),
('Coffee Jelly Frappe', 'Coffee', 140.00, 'src\\products\\Coffee Jelly Frappes.jpg'),
('Caramel Frappe', 'Coffee', 140.00, 'src\\products\\Caramel Frappes.jpg'),
('Creamy Vanilla Frappe', 'Coffee', 150.00, 'src\\products\\Creamy Vanilla Frappes.jpg'),
('Java Chips Frappe', 'Coffee', 150.00, 'src\\products\\Java Chips Frappes.jpg'),
('Java Peppermint Frappe', 'Coffee', 150.00, 'src\\products\\Java Peppermint Frappes.jpg'),
('Praline Mocha Frappe', 'Coffee', 155.00, 'src\\products\\Praline Mocha Frappes.jpg'),
('Almond Praline Frappe', 'Coffee', 155.00, 'src\\products\\Almond Praline Frappes.jpg'),
('Dark Mocha Frappe', 'Coffee', 165.00, 'src\\products\\Dark Mocha Frappes.jpg'),
('White Mocha Frappe', 'Coffee', 165.00, 'src\\products\\White Mocha Frappes.jpg'),
('Chocolate Milk Frappe', 'Coffee', 140.00, 'src\\products\\Chocolate Milk Frappes.jpg'),
('Milky Caramel Frappe', 'Coffee', 140.00, 'src\\products\\Caramel Frappes.jpg'),
('Milky Creamy Vanilla Frappe', 'Coffee', 150.00, 'src\\products\\Creamy Vanilla Frappes.jpg'),
('Cookies N'' Cream Frappe', 'Coffee', 155.00, 'src\\products\\Cookies N'' Cream Milk Frappes.jpg'),
('Dark Chocolate with Cheese Frappe', 'Coffee', 165.00, 'src\\products\\Dark Chocolate Milk Frappes.jpg'),
('White Chocolate Frappe', 'Coffee', 165.00, 'src\\products\\White Chocolate Milk Frappes.jpg'),
('Creamy Mango Tea', 'Tea', 125.00, 'src\\products\\Creamy Mango Fruit Smoothies.jpg'),
('Milky Strawberry Tea', 'Tea', 150.00, 'src\\products\\Milky Strawberry Fruit Smoothies.jpg'),
('Melon with Collagen Tea', 'Tea', 150.00, 'src\\products\\Melon with Collagen Fruit Smoothies.jpg'),
('Assam Tea', 'Tea', 90.00, 'src\\products\\Assam Milk Tea.jpg'),
('Coffee Jelly Tea', 'Tea', 95.00, 'src\\products\\Coffee Jelly Milk Tea.jpg'),
('Chocolate Tea', 'Tea', 95.00, 'src\\products\\Chocolate Milk Tea.jpg'),
('Brown Sugar Tea', 'Tea', 95.00, 'src\\products\\Brown Sugar Tea.jpg'),
('Oreo Cookies Tea', 'Tea', 95.00, 'src\\products\\Oreo Cookies.jpg'),
('Wintermelon Tea', 'Tea', 100.00, 'src\\products\\Wintermelon Milk TEa.jpg'),
('Okinawa Tea', 'Tea', 100.00, 'src\\products\\Okinawa Milk Tea.jpg'),
('Strawberry Cream Tea', 'Tea', 100.00, 'src\\products\\Strawberry Cream Milk Tea.jpg'),
('Matcha Tea', 'Tea', 110.00, 'src\\products\\Matcha Milk TEa.jpg'),
('Red Velvet Tea', 'Tea', 100.00, 'src\\products\\Red Velvet Milk Tea.jpg'),
('Cheesecake Tea', 'Tea', 100.00, 'src\\products\\Cheesecake Milk Tea.jpg'),
('Dark Choco Tea', 'Tea', 90.00, 'src\\products\\Dark Choco Milk Tea.jpg'),
('Taro Tea', 'Tea', 90.00, 'src\\products\\Taro Milk TEa.jpg'),
('Choco Kisses Tea', 'Tea', 90.00, 'src\\products\\Choco Kisses Milk TEa.jpg'),
('Salted Caramel Tea', 'Tea', 100.00, 'src\\products\\Brown Sugar Milk Tea.jpg'),
('Double Dutch Tea', 'Tea', 100.00, 'src\\products\\Double Dutch Milk Tea.jpg'),
('Mint Tea', 'Tea', 70.00, 'src\\products\\Mint Hot Tea.jpg'),
('Green Tea', 'Tea', 70.00, 'src\\products\\Assam Tea Latte.jpg'),
('Strawberry Tea Latte', 'Tea', 70.00, 'src\\products\\Strawberry Tea Latte.jpg'),
('Earl Grey Tea', 'Tea', 70.00, 'src\\products\\Earl Grey Hot Tea.jpg'),
('Raspberry Tea', 'Tea', 130.00, 'src\\products\\Raspberry Fruit Tea.jpg'),
('Assam Tea Latte', 'Tea', 90.00, 'src\\products\\Assam Tea Latte.jpg'),
('Okinawa Tea Latte', 'Tea', 100.00, 'src\\products\\Okinawa Tea Latte.jpg'),
('Matcha Tea Latte', 'Tea', 110.00, 'src\\products\\Matcha Tea Latte.jpg'),
('Oatmeal Cookie', 'Snacks', 25.00, 'src\\products\\Oatmeal Cookie.jpg'),
('Chocolate Cookie', 'Snacks', 30.00, 'src\\products\\Chocolate Cookie.jpg'),
('Delisioso Pan Tostado', 'Snacks', 85.00, 'src\\products\\Delisioso Pan Tostado.jpg'),
('Tuna Sandwich', 'Snacks', 100.00, 'src\\products\\Tuna Sandwich.jpg'),
('Beefy Nachos', 'Snacks', 115.00, 'src\\products\\Beefy Nachos.jpg'),
('Clubhouse Sandwich', 'Snacks', 125.00, 'src\\products\\Clubhouse Sandwich.jpg'),
('Ube Halaya', 'Snacks', 125.00, 'src\\products\\Ube Halaya.jpg'),
('Chocolate Cake', 'Snacks', 145.00, 'src\\products\\Chocolate Cake.jpg'),
('Cheesecake', 'Snacks', 150.00, 'src\\products\\Cheesecake.jpg'),
('Ice Cream Cake', 'Snacks', 150.00, 'src\\products\\Ice Cream Cake.jpg'),
('Birthday Cake', 'Snacks', 150.00, 'src\\products\\Birthday Cake.jpg'),
('Red Velvet Cake', 'Snacks', 150.00, 'src\\products\\Red Velvet Cake.jpg'),
('Chocolate Chip Cookies', 'Snacks', 150.00, 'src\\products\\Chocolate Chip Cookies.jpg'),
('Jelly Beans', 'Snacks', 150.00, 'src\\products\\Jelly Beans.jpg'),
('Cheese Bread', 'Snacks', 150.00, 'src\\products\\Cheese Bread.jpg'),
('Cupcakes', 'Snacks', 150.00, 'src\\products\\Cupcakes.jpg'),
('Bread Roll', 'Snacks', 150.00, 'src\\products\\Bread Roll.jpg');
