* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Other/SQLTemplate.sql to edit this template
 */
/**
 * Author:  James
 * Created: Sep 27, 2024
 */

INSERT INTO `tbl_products` (`product_name`, `product_category`, `product_price`, `product_ImagePath`) VALUES
('Classic Brewed Coffee', 'Coffee', 70.00, 'src\\products\\Almond Praline Hot.jpg'),
('French Pressed Brewed Coffee', 'Coffee', 90.00, 'src\\products\\Almond Praline Hot.jpg'),
('Caffe Latte', 'Coffee', 90.00, 'src\\products\\Almond Praline Hot.jpg'),
('Cappuccino', 'Coffee', 90.00, 'src\\products\\Almond Praline Hot.jpg'),
('Caffe Mocha', 'Coffee', 100.00, 'src\\products\\Almond Praline Hot.jpg'),
('Caramel Macchiato', 'Coffee', 105.00, 'src\\products\\Almond Praline Hot.jpg'),
('Caramel Latte', 'Coffee', 105.00, 'src\\products\\Almond Praline Hot.jpg'),
('Almond Latte', 'Coffee', 105.00, 'src\\products\\Almond Praline Hot.jpg'),
('Vanilla Latte', 'Coffee', 105.00, 'src\\products\\Almond Praline Hot.jpg'),
('Praline Mocha', 'Coffee', 110.00, 'src\\products\\Almond Praline Hot.jpg'),
('Almond Praline', 'Coffee', 110.00, 'src\\products\\Almond Praline Hot.jpg'),
('Dark Mocha', 'Coffee', 120.00, 'src\\products\\Almond Praline Hot.jpg'),
('White Mocha', 'Coffee', 120.00, 'src\\products\\Almond Praline Hot.jpg'),
('Iced Caffe Latte', 'Coffee', 110.00, 'src\\products\\Almond Praline Hot.jpg'),
('Coffee Jelly', 'Coffee', 130.00, 'src\\products\\Almond Praline Hot.jpg'),
('Iced Caffe Mocha', 'Coffee', 130.00, 'src\\products\\Almond Praline Hot.jpg'),
('Iced Caramel', 'Coffee', 130.00, 'src\\products\\Almond Praline Hot.jpg'),
('Iced Almond Latte', 'Coffee', 130.00, 'src\\products\\Almond Praline Hot.jpg'),
('Iced Caramel Macchiato', 'Coffee', 135.00, 'src\\products\\Almond Praline Hot.jpg'),
('Iced Creamy Vanilla', 'Coffee', 140.00, 'src\\products\\Almond Praline Hot.jpg'),
('Iced Praline Mocha', 'Coffee', 145.00, 'src\\products\\Almond Praline Hot.jpg'),
('Iced Almond Praline', 'Coffee', 145.00, 'src\\products\\Almond Praline Hot.jpg'),
('Iced Dark Mocha', 'Coffee', 145.00, 'src\\products\\Almond Praline Hot.jpg'),
('Iced White Mocha', 'Coffee', 145.00, 'src\\products\\Almond Praline Hot.jpg'),
('Mocha Frappe', 'Coffee', 140.00, 'src\\products\\Almond Praline Hot.jpg'),
('Coffee Jelly Frappe', 'Coffee', 140.00, 'src\\products\\Almond Praline Hot.jpg'),
('Caramel Frappe', 'Coffee', 140.00, 'src\\products\\Almond Praline Hot.jpg'),
('Creamy Vanilla Frappe', 'Coffee', 150.00, 'src\\products\\Almond Praline Hot.jpg'),
('Java Chips Frappe', 'Coffee', 150.00, 'src\\products\\Almond Praline Hot.jpg'),
('Java Peppermint Frappe', 'Coffee', 150.00, 'src\\products\\Almond Praline Hot.jpg'),
('Praline Mocha Frappe', 'Coffee', 155.00, 'src\\products\\Almond Praline Hot.jpg'),
('Almond Praline Frappe', 'Coffee', 155.00, 'src\\products\\Almond Praline Hot.jpg'),
('Dark Mocha Frappe', 'Coffee', 165.00, 'src\\products\\Almond Praline Hot.jpg'),
('White Mocha Frappe', 'Coffee', 165.00, 'src\\products\\Almond Praline Hot.jpg'),
('Chocolate Milk Frappe', 'Coffee', 140.00, 'src\\products\\Almond Praline Hot.jpg'),
('Milky Caramel Frappe', 'Coffee', 140.00, 'src\\products\\Almond Praline Hot.jpg'),
('Milky Creamy Vanilla Frappe', 'Coffee', 150.00, 'src\\products\\Almond Praline Hot.jpg'),
('Cookies N\' Cream Frappe', 'Coffee', 155.00, 'src\\products\\Almond Praline Hot.jpg'),
('Dark Chocolate with Cheese Frappe', 'Coffee', 165.00, 'src\\products\\Almond Praline Hot.jpg'),
('White Chocolate Frappe', 'Coffee', 165.00, 'src\\products\\Almond Praline Hot.jpg'),
('Creamy Mango Tea', 'Tea', 125.00, 'src\\products\\Okinawa Milk Tea.jpg'),
('Milky Strawberry Tea', 'Tea', 150.00, 'src\\products\\Okinawa Milk Tea.jpg'),
('Melon with Collagen Tea', 'Tea', 150.00, 'src\\products\\Okinawa Milk Tea.jpg'),
('Assam Tea', 'Tea', 90.00, 'src\\products\\Okinawa Milk Tea.jpg'),
('Coffee Jelly Tea', 'Tea', 95.00, 'src\\products\\Okinawa Milk Tea.jpg'),
('Chocolate Tea', 'Tea', 95.00, 'src\\products\\Okinawa Milk Tea.jpg'),
('Brown Sugar Tea', 'Tea', 95.00, 'src\\products\\Okinawa Milk Tea.jpg'),
('Oreo Cookies Tea', 'Tea', 95.00, 'src\\products\\Okinawa Milk Tea.jpg'),
('Wintermelon Tea', 'Tea', 100.00, 'src\\products\\Okinawa Milk Tea.jpg'),
('Okinawa Tea', 'Tea', 100.00, 'src\\products\\Okinawa Milk Tea.jpg'),
('Strawberry Cream Tea', 'Tea', 100.00, 'src\\products\\Okinawa Milk Tea.jpg'),
('Matcha Tea', 'Tea', 110.00, 'src\\products\\Okinawa Milk Tea.jpg'),
('Red Velvet Tea', 'Tea', 100.00, 'src\\products\\Okinawa Milk Tea.jpg'),
('Cheesecake Tea', 'Tea', 100.00, 'src\\products\\Okinawa Milk Tea.jpg'),
('Dark Choco Tea', 'Tea', 90.00, 'src\\products\\Okinawa Milk Tea.jpg'),
('Taro Tea', 'Tea', 90.00, 'src\\products\\Okinawa Milk Tea.jpg'),
('Choco Kisses Tea', 'Tea', 90.00, 'src\\products\\Okinawa Milk Tea.jpg'),
('Salted Caramel Tea', 'Tea', 100.00, 'src\\products\\Okinawa Milk Tea.jpg'),
('Double Dutch Tea', 'Tea', 100.00, 'src\\products\\Okinawa Milk Tea.jpg'),
('Mint Tea', 'Tea', 70.00, 'src\\products\\Okinawa Milk Tea.jpg'),
('Green Tea', 'Tea', 70.00, 'src\\products\\Okinawa Milk Tea.jpg'),
('Strawberry Tea Latte', 'Tea', 70.00, 'src\\products\\Okinawa Milk Tea.jpg'),
('Earl Grey Tea', 'Tea', 70.00, 'src\\products\\Okinawa Milk Tea.jpg'),
('Raspberry Tea', 'Tea', 130.00, 'src\\products\\Okinawa Milk Tea.jpg'),
('Assam Tea', 'Tea', 90.00, 'src\\products\\Okinawa Milk Tea.jpg'),
('Okinawa Tea Latte', 'Tea', 100.00, 'src\\products\\Okinawa Milk Tea.jpg'),
('Matcha Tea Latte', 'Tea', 110.00, 'src\\products\\Okinawa Milk Tea.jpg'),
('Oatmeal Cookie', 'Snacks', 25.00, 'src\\products\\Grilled Cheese Sandwich.jpg'),
('Chocolate Cookie', 'Snacks', 30.00, 'src\\products\\Grilled Cheese Sandwich.jpg'),
('Delisioso Pan Tostado', 'Snacks', 85.00, 'src\\products\\Grilled Cheese Sandwich.jpg'),
('Tuna Sandwich', 'Snacks', 100.00, 'src\\products\\Grilled Cheese Sandwich.jpg'),
('Beefy Nachos', 'Snacks', 115.00, 'src\\products\\Grilled Cheese Sandwich.jpg'),
('Clubhouse Sandwich', 'Snacks', 125.00, 'src\\products\\Grilled Cheese Sandwich.jpg'),
('Ube Halaya', 'Snacks', 125.00, 'src\\products\\Grilled Cheese Sandwich.jpg'),
('Corn Dog', 'Snacks', 70.00, 'src\\products\\Grilled Cheese Sandwich.jpg'),
('Grilled Cheese Sandwich', 'Snacks', 90.00, 'src\\products\\Grilled Cheese Sandwich.jpg');
